test job

diff --git a/.github/workflows/is-version-incremented.yaml b/.github/workflows/is-version-incremented.yaml
--- a/.github/workflows/is-version-incremented.yaml
+++ b/.github/workflows/is-version-incremented.yaml
@@ -14,23 +14,23 @@ jobs:
         uses: actions/checkout@v3
       - name: Git Diff
         run: |
-               base="${{ github.event.pull_request.base.ref }}"
-               head="${{ github.event.pull_request.head.ref }}"
-               git fetch origin ${base}:refs/remotes/origin/${base}
-               path=$(git diff --name-only origin/${base} | grep pom.xml)
-               if [ -z "${path}" ]
-               then
-               echo "Cannot find pom.xml in changed files"
-               exit 1
-               else
-               diff=$(git diff origin/${base} ${path} | | sed -e 's| ||g')
-               was=$(echo "${diff}" \
-               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
-               become=$(echo "${diff}" \
-               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
-               echo "WAS -- ${was}"
-               echo "become -- ${become}"
-               fi
+          base="${{ github.event.pull_request.base.ref }}"
+          head="${{ github.event.pull_request.head.ref }}"
+          git fetch origin ${base}:refs/remotes/origin/${base}
+          path=$(git diff --name-only origin/${base} | grep pom.xml)
+          if [ -z "${path}" ]
+          then
+          echo "Cannot find pom.xml in changed files"
+          exit 1
+          else
+          diff=$(git diff origin/${base} ${path} | | sed -e 's| ||g')
+          was=$(echo "${diff}" \
+          | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
+          become=$(echo "${diff}" \
+          | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
+          echo "WAS -- ${was}"
+          echo "become -- ${become}"
+          fi
 
 
 
