test job

diff --git a/.github/workflows/is-version-incremented.yaml b/.github/workflows/is-version-incremented.yaml
--- a/.github/workflows/is-version-incremented.yaml
+++ b/.github/workflows/is-version-incremented.yaml
@@ -14,10 +14,28 @@ jobs:
         uses: actions/checkout@v3
       - name: Git Diff
         run: |
-          base="${{ github.event.pull_request.base.ref }}"
-          head="${{ github.event.pull_request.head.ref }}"
-          git fetch origin ${base}:refs/remotes/origin/${base}
-          git diff --name-only origin/${base}
+          #         if pull request
+               base="${{ github.event.pull_request.base.ref }}"
+               head="${{ github.event.pull_request.head.ref }}"
+               git fetch origin ${base}:refs/remotes/origin/${base}
+          #         if pom.xml
+               path=$(git diff --name-only origin/${base} | grep pom.xml)
+               if [ -z "${path}" ]
+               then
+               echo "Cannot find pom.xml in changed files"
+               exit 1
+               else
+               diff=$(git diff origin/${base} ${path} | | sed -e 's| ||g')
+               was=$(echo "${diff}" \
+               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
+               become=$(echo "${diff}" \
+               | grep -Po "(?<=^-<version>)((\d+|.)+?)(?=<\/version>))
+               echo "WAS -- ${was}"
+               echo "become -- ${become}"
+               fi
+
+
+
 #          echo ${{ github.event.pull_request.base.ref }}
 #          echo ${{ github.event.pull_request.head.ref }}
 #          more $GITHUB_EVENT_PATH
